# /etc/flexget/config.yml 
templates:
  tv:

#    manipulate:
#      - title: &the
#          replace:
#            regexp: '^The\W'
#            format: ''
#      - filename: *the
#      - series_name: *the

    private_torrents: no

    series:
      settings:
        tv:
          exact: yes
          propers: 2 days
          quality: HDTV
          set:
            path: "/[path to]/[folder in lxc]/[to save media to]/{{series_name}}"
            
      tv:
        - series_A
        - series_B
        - series_C

    transmission:
      enabled: yes
      host: localhost
      port: 9091
      username: transmission
      password: [password for transmission-daemon]

tasks:

  rss.site.name.1:
    priority: 1
    rss: [url.for.rss_site]
    template: tv

  rss.site.name.2:
    priority: 2
    rss: [url.for.rss_site2]
    template: tv
    verify_ssl_certificates: no

  rss.site.name.3:
    priority: 3
    rss: [url.for.rss_site3]
    template: tv
